s9y/additional_plugins

serendipity_plugin_piwik/ChangeLog, serendipity_plugin_piwik/README.markdown, serendipity_plugin_piwik/UTF-8/lang_de.inc.php, serendipity_plugin_piwik/UTF-8/lang_en.inc.php, serendipity_plugin_piwik/lang_de.inc.php, serendipity_plugin_piwik/lang_en.inc.php, serendipity_plugin_piwik/serendipity_plugin_piwik.php
Sidebar plugin for Piwik to show last xx most viewed entries within last yy days.
=> first piwik-sidebar-commit

serendipity_event_ljupdate/serendipity_event_ljupdate.php
Fix runtime error raised while displaying new/edit post page.
Also use default userpic in LiveJournal when userpic not selected in serendipity post.
=> serendipity_event_ljupdate: Fix XML-RPC results reading bug

serendipity_event_dejure/UTF-8/lang_de.inc.php, serendipity_event_dejure/lang_de.inc.php, serendipity_event_dejure/lang_en.inc.php, serendipity_event_dejure/serendipity_event_dejure.php
v1.5 taken from <https://dejure.org/vernetzung.html> with author's consent.
Some minor changes to the database queries, trying to be more compatible to other database backends, see <https://board.s9y.org/viewtopic.php?f=10&t=21255>.
Update language files (as far as I speak those languages).
Tested on my live-blog.
=> Update dejure-plugin to version 1.5 from upstream.

serendipity_event_galleryimage/serendipity_event_galleryimage.php
replaced preg_replace /e with preg_replace_callback
pls ignore the earlier pull-request, this is the correct one.
=> PHP7 compatibility for event_galleryimage

serendipity_event_dejure/ChangeLog, serendipity_event_dejure/documentation_de.html, serendipity_event_dejure/serendipity_event_dejure.php
Try. Fail. Try again, fail better.
=> Fix HTML of local documentation.

alpha/serendipity_event_challengeresponse.php
in order to comply with W3C WAI
s9y comment form is using this already
=> add label element to challengeresponse

serendipity_event_lightbox/UTF-8/lang_de.inc.php, serendipity_event_lightbox/lang_de.inc.php, serendipity_event_lightbox/lang_en.inc.php
See <https://board.s9y.org/viewtopic.php?f=4&t=21212#p10448209>.
=> [serendipity_event_lightbox] Improve description.

serendipity_event_entrycheck/serendipity_event_entrycheck.php
Modification made to use PR https://github.com/s9y/Serendipity/pull/544
=> Adapt serendipity_event_entrycheck to 2k11 admin interface

serendipity_event_gravatar/serendipity_event_gravatar.php
=> [event_gravatar] Fix paste error in legal info.

serendipity_event_markdown/ChangeLog, serendipity_event_markdown/lib/License.md, serendipity_event_markdown/lib/Michelf/Markdown.php, serendipity_event_markdown/lib/Michelf/MarkdownExtra.php, serendipity_event_markdown/lib/Michelf/MarkdownInterface.php, serendipity_event_markdown/lib/Michelf/SmartyPants.php, serendipity_event_markdown/lib/Michelf/SmartyPantsTypographer.php, serendipity_event_markdown/lib/Readme.md, serendipity_event_markdown/lib/Readme.php, serendipity_event_markdown/lib/composer.json, serendipity_event_markdown/serendipity_event_markdown.php
- Update Markdown Lib to 1.8.0.
- Update SmartyPants Lib to 1.8.1.
=> [markdown] Upgrade Markdown Lib and SmartyPants Lib.

serendipity_event_entrylastmodified/ChangeLog, serendipity_event_entrylastmodified/UTF-8/lang_de.inc.php, serendipity_event_entrylastmodified/lang_de.inc.php, serendipity_event_entrylastmodified/serendipity_event_entrylastmodified.php
Add/enhance German translation.
Add ChangeLog.
=> entrylastmodified: Add/enhance German translation.

serendipity_event_vgwort/ChangeLog, serendipity_event_vgwort/UTF-8/lang_de.inc.php, serendipity_event_vgwort/UTF-8/lang_en.inc.php, serendipity_event_vgwort/serendipity_event_vgwort.php, serendipity_event_vgwort/vgwortMenu.tpl
* Change type of UNIQUE columns to VARCHAR. 
* Requires at least s9y 2.2.1-alpha1, s9y/Serendipity#511
* Fix a typo ("==" must be "=" in MySQL).
* Fix a typo (string concatenation is ".=", not "+=").
=> vgwort: Some fixes.

serendipity_plugin_flickrbadge/ChangeLog, serendipity_plugin_flickrbadge/lib/flickr.php, serendipity_plugin_flickrbadge/serendipity_plugin_flickrbadge.php
* serendipity_plugin_flickrbadge
(serendipity_plugin_flickr remains still to be done.)
=> Change HTTP/Request to serendipity_request_url().

serendipity_event_google_sitemap/ChangeLog, serendipity_event_google_sitemap/UTF-8/lang_de.inc.php, serendipity_event_google_sitemap/lang_de.inc.php, serendipity_event_google_sitemap/lang_en.inc.php, serendipity_event_google_sitemap/serendipity_event_google_sitemap.php
See https://github.com/s9y/Serendipity/issues/601, requesting Review from @hannob
=> sitemap 0.60: Kick noindex pages out of the sitemap

serendipity_event_aggregator/serendipity_event_aggregator.php
each() is deprecated in current php versions
=> serendipity_event_aggregator fixes for php7.3

serendipity_event_metadesc/ChangeLog, serendipity_event_metadesc/serendipity_event_metadesc.php, serendipity_event_social/ChangeLog, serendipity_event_social/serendipity_event_social.php
* Fix accidental deletion of metadesc data.
* Fix accidental deletion of entry_image.
See  s9y/Serendipity#688.
=> Fix accidental deletion of extended properties.

serendipity_event_microformats/serendipity_plugin_microformats.php
Otherwise PostgreSQL will throw an "operator does not exist" error
=> Add CAST for "value" column when selecting mf_hCalendar data

serendipity_event_geo_json/ChangeLog, serendipity_event_geo_json/plugin_version.inc.php, serendipity_event_geo_json/serendipity_event_geo_json.php
=> updated event_geo_json to v0.2.2

serendipity_event_osm/ChangeLog, serendipity_event_osm/UTF-8/lang_de.inc.php, serendipity_event_osm/lang_de.inc.php, serendipity_event_osm/lang_en.inc.php, serendipity_event_osm/plugin_version.inc.php, serendipity_event_osm/ressources/osm.js, serendipity_event_osm/serendipity_event_osm.php
Avoid using translation from page nugget
Preloading enabled
Show track length in link title
=> Updated event_osm to v0.3.4

alpha/serendipity_event_communityrating/serendipity_event_communityrating.php, alpha/serendipity_event_communityrating/serendipity_plugin_communityrating.php, alpha/serendipity_event_communityrating/smarty.inc.php, alpha/serendipity_event_findmore/serendipity_event_findmore.php, alpha/serendipity_event_picasa/serendipity_event_picasa.php
INCLUDE_ANY is not quoted
Fix: #720
=> Fix PHP warning about undefined constants

serendipity_event_osm/ChangeLog, serendipity_event_osm/UTF-8/lang_de.inc.php, serendipity_event_osm/lang_de.inc.php, serendipity_event_osm/lang_en.inc.php, serendipity_event_osm/plugin_version.inc.php, serendipity_event_osm/ressources/osm.js, serendipity_event_osm/serendipity_event_osm.php, serendipity_event_osm/serendipity_event_static_osm.php
* Plugin dependencies added
* More understandable translations
* Performance updates
* Count distances only once
* Bugfix for "no categories"
* Added missing php 7.0 dependency
* Preloading fixed
=> Updated event_osm to v0.3.5

serendipity_plugin_shoutbox/ChangeLog, serendipity_plugin_shoutbox/serendipity_plugin_shoutbox.php
* Use serendipity_db_escape_string and avoid sprintf
=> updated plugin_shoutbox to v1.02.4

serendipity_event_osm/ChangeLog, serendipity_event_osm/plugin_version.inc.php, serendipity_event_osm/ressources/osm.js, serendipity_event_osm/serendipity_event_static_osm.php
* Using VectorImage instead of Vector
* Fixed compressed *.gpx size bug
* Compress *.gpx files only
=> Updated event_osm to v0.3.6

serendipity_event_geotag/ChangeLog, serendipity_event_geotag/plugin_version.inc.php, serendipity_event_geotag/serendipity_event_geotag.php
=> Updated event_geotag to v01.36

serendipity_event_osm/ChangeLog, serendipity_event_osm/README.md, serendipity_event_osm/UTF-8/lang_de.inc.php, serendipity_event_osm/lang_de.inc.php, serendipity_event_osm/lang_en.inc.php, serendipity_event_osm/plugin_version.inc.php, serendipity_event_osm/serendipity_event_osm.php, serendipity_event_osm/serendipity_event_static_osm.php
* Added README.md
* Set default category id to "without"
* Escape map parameter
* Path description fixed for many paths
* Default path for *.gpx files
=> Updated event_osm to v0.3.7

serendipity_event_geo_json/ChangeLog, serendipity_event_geo_json/UTF-8/lang_de.inc.php, serendipity_event_geo_json/UTF-8/lang_es.inc.php, serendipity_event_geo_json/lang_de.inc.php, serendipity_event_geo_json/lang_en.inc.php, serendipity_event_geo_json/lang_es.inc.php, serendipity_event_geo_json/plugin_version.inc.php, serendipity_event_geo_json/serendipity_event_geo_json.php
Update event_geo_json to 0.3.0
* Added Spanish translations
* Improved translations
* More generic JSON data
* Changed my name
=> Update geo json

serendipity_event_freetag/ChangeLog, serendipity_event_freetag/serendipity_event_freetag.php
Reported in https://github.com/s9y/Serendipity/issues/858
=> freetag 3.70.9: Avoid php warnings in RSS feed

serendipity_event_commentspice/ChangeLog, serendipity_event_commentspice/serendipity_event_commentspice.php
Reported in https://github.com/s9y/Serendipity/issues/851
=> commentspice 1.10.2: Fix some PHP warnings

serendipity_event_weblogping/ChangeLog, serendipity_event_weblogping/serendipity_event_weblogping.php, serendipity_event_weblogping/servicesdb_de.inc.php, serendipity_event_weblogping/servicesdb_en.inc.php, serendipity_event_weblogping/servicesdb_ja.inc.php, serendipity_event_weblogping/servicesdb_tn.inc.php
Removes sites that got shut down (almost all of them) and the HTTP/Request fallback code, as that lib is removed for a while now.
=> weblogping 1.10: Remove outdated services and code

serendipity_event_google_analytics/ChangeLog, serendipity_event_google_analytics/serendipity_event_google_analytics.php, serendipity_event_userprofiles/ChangeLog, serendipity_event_userprofiles/serendipity_event_userprofiles.php, serendipity_event_userprofiles/serendipity_plugin_userprofiles.php, serendipity_event_userprofiles/serendipity_plugin_userprofiles_birthdays.php
A cleaned up version of https://github.com/s9y/additional_plugins/pull/167, with only the relevant commit. Also raises versions and describes changes.
=> analytics 2.0.2, userprofiles 0.31.4: Avoid dynamic properties warning

serendipity_event_staticpage/serendipity_event_staticpage.php
Fixes https://github.com/s9y/Serendipity/issues/880
=> staticpage 4.15.11: Fix mysql error caused by INDEX IF NOT EXISTS

serendipity_plugin_adduser/ChangeLog, serendipity_plugin_adduser/common.inc.php, serendipity_plugin_adduser/serendipity_event_adduser.php, serendipity_plugin_adduser/serendipity_plugin_adduser.php
See https://board.s9y.org/viewtopic.php?p=10459169#p10459169 for a (possible) context
=> adduser 2.40.3: PHP 8 fixes & avoid db error on first registration
