s9y/additional_plugins

serendipity_event_social/serendipity_event_social.php

Currently s9y_event_social is using the first 200 chars of the entry body for the "og:description" meta tag.
The plugin s9y_event_metadesc makes it possible to specify a description for every entry that is used to set the "description" meta tag.  This description, if present, should be used for the "og:description" meta tag, too. Using the first 200 chars can remain as a fallback solution.
At least the description from s9y_event_metadesc needs to be HTML-escaped. I think that goes for the first 200 chars from the body, too.
See http://board.s9y.org/viewtopic.php?f=10&t=20762&start=75 for a discussion (in German).

s9_event_social: Set og:description from s9y_event_metadesc.

---

serendipity_event_social/serendipity_event_social.php

Quotes in a manually supplied description - or the first
200 characters of the entry body - have to be escaped
before the text can become the content attribute of
the og:description meta tag.
It doesn't hurt to escape everything, then.

Escape special chars in description.

---

serendipity_event_metadesc/ChangeLog
serendipity_event_metadesc/serendipity_event_metadesc.php

fc87b5f6d700945fd06836dd2433d80c43984a18 has changed
the way the "body" content was accessed from
$GLOBALS['entry'][0]
to
$entry,
but didn't drop the "[0]" everywhere.

Fix kind of copy-paste-error.

---

serendipity_event_commentspice/ChangeLog
serendipity_event_commentspice/serendipity_event_commentspice.php

Removed leading "http:" from the link to the twitter widget script. This avoids a broken security chain when the blog uses https.

Fix adress for twitter widget

---

serendipity_event_recaptcha/UTF-8/lang_cs.inc.php
serendipity_event_recaptcha/UTF-8/lang_cz.inc.php
serendipity_event_recaptcha/UTF-8/lang_de.inc.php
serendipity_event_recaptcha/lang_cs.inc.php
serendipity_event_recaptcha/lang_cz.inc.php
serendipity_event_recaptcha/lang_de.inc.php
serendipity_event_recaptcha/lang_en.inc.php
serendipity_event_recaptcha/serendipity_event_recaptcha.php

The in-plugin documentation (descriptions) show old URLs from recaptcha.net instead of the current ones from Google.
Those old URLs are defined in the plugin code, too, but never used.
Thanks to Imajica for the heads-up in https://board.s9y.org/viewtopic.php?f=2&t=21037

Update recaptcha URLs

---

serendipity_event_markdown/ChangeLog
serendipity_event_markdown/lib/License.md
serendipity_event_markdown/lib/Michelf/Markdown.inc.php
serendipity_event_markdown/lib/Michelf/Markdown.php
serendipity_event_markdown/lib/Michelf/MarkdownExtra.inc.php
serendipity_event_markdown/lib/Michelf/MarkdownExtra.php
serendipity_event_markdown/lib/Michelf/MarkdownInterface.inc.php
serendipity_event_markdown/lib/Michelf/MarkdownInterface.php
serendipity_event_markdown/lib/Readme.md
serendipity_event_markdown/lib/Readme.php
serendipity_event_markdown/lib/composer.json
serendipity_event_markdown/serendipity_event_markdown.php

* The "classic" PHP Markdown version is no longer updated since 02/2013.
* Upgrade PHP Markdown Lib to 1.7.0 
* Get MarkdownExtra working with PHP Markdown Lib
It's not enough to import the right library (Markdown or MarkdownExtra); you'll have to call the right functions, too!
* Update Changelog, bump version to 1.23, add my as author
Tested on my dev blog and my live blog, no regressions AFAICS.

Update PHP Markdown lib and get MarkdownExtra working.

---

serendipity_event_social/ChangeLog
serendipity_event_social/serendipity_event_social.php

See <https://board.s9y.org/viewtopic.php?f=4&t=21256&p=10447310#p10447310>.
`$GLOBALS['entry']` doesn't contain any data any longer in 2.1, AFAICS.

Get rid of $GLOBALS['entry'].

---

serendipity_event_markdown/ChangeLog
serendipity_event_markdown/serendipity_event_markdown.php

Add the entry id as a prefix to every footnote links so links are unique even when more than one entry is displayed (title page, search results etc.).
This can only be done with PHP Markdown Lib; the "classic" version does not have such a configuration variable.
Tested on my devblog.

Add a prefix for footnote links.

---

serendipity_event_dejure/serendipity_event_dejure.php

v1.6 was not yet published.
Improve fsockopen, switch to SSL, add user agent.
Tested on my live-blog in production.

Update dejure-plugin to version 1.6 from upstream.

---

serendipity_event_dejure/ChangeLog
serendipity_event_dejure/documentation_de.html
serendipity_event_dejure/serendipity_event_dejure.php

German language only, as there will be very little need to link to German law and decisions in a foreign language blog.

Add local documentation to dejure.org plugin.

---

serendipity_event_dejure/serendipity_event_dejure.php

The declaration of uninstall() didn't match serendipity_plugin::uninstall, making PHP spew warnings to the log.

Fix function definition.

---

serendipity_event_mobile_output/serendipity_event_mobile_output.php
serendipity_event_staticpage/serendipity_event_staticpage.php
serendipity_plugin_twitter/serendipity_event_twitter.php
serendipity_plugin_twitter/serendipity_plugin_twitter.php

The 'website' property of plugins is used to link to external documentation. board.s9y.org does not contain such documentation; c.seo-mobile.de does no longer exist.

Remove dead or useless links to external plugin documentation.

---

emerge_spartacus.php

It would be nice to be able to link directly to a certain plugin, so add ids to the generated HTML.
Using the plugin name should make for unique ids without illegal characters.
As I'm not really familiar with this code and have no test installation, I'd like a review before merging, please. :-)

Add ids as link targets to spartacus web pages.

---

emerge_spartacus.php

This adds just a little convenient link to each plugin's `id` in additions to @th-h's #70 – picking that out of the markup seemed tedious. :)

Add convenience link to single plugins on spartacus

---

serendipity_event_google_sitemap/serendipity_event_google_sitemap.php

With google going https by default it makes sense to use the HTTPS url for sitemap submissions. Also the sitemap.org protocol spec redirects all requests to HTTPS, so change that url as well.

change google.com and sitemap.org URLs to https

---

serendipity_event_google_sitemap/serendipity_event_google_sitemap.php

Remove obsolete ask.com submission URL, see:
https://board.s9y.org/viewtopic.php?f=3&t=17239

remove submissions.ask.com, no longer exists

---

serendipity_event_dsgvo_gdpr/ChangeLog
serendipity_event_dsgvo_gdpr/serendipity_event_dsgvo_gdpr.php

I think https://www.datenschutz-guru.de/braucht-mein-kontaktformular-jetzt-eine-checkbox/ is convincing and I remember we saw it like that as well. The checkbox should not be on by default then - this PR does that.

dsgvo: set default of commentform checkbox to false

---

serendipity_event_dsgvo_gdpr/ChangeLog
serendipity_event_dsgvo_gdpr/UTF-8/lang_de.inc.php
serendipity_event_dsgvo_gdpr/lang_de.inc.php
serendipity_event_dsgvo_gdpr/lang_en.inc.php
serendipity_event_dsgvo_gdpr/serendipity_event_dsgvo_gdpr.php

I was annoyed when having to recreate the markup of the privacy notice draft. This adds a button that copies the html fro ma textarea into the clipboard, making it easy for the user to set the draft as his privacy notice. 
It also adds some newlines to the themes section to make it easier to edit that part.

Add a button to the privacy draft to copy the pure html

---

serendipity_event_externalphp/serendipity_event_externalphp.php

Just like the static pages plugin the external PHP plugin overrides the 404 error handling. The content from the external PHP script is displayed as expected but above this content the error message from the language constant URL_NOT_FOUND is shown. The static pages plugin resets this error message to get rid of the error message. The change in this commit does exactly the same thing for the external PHP plugin.

Reset 404 error message for external PHP plugin

---

serendipity_event_dsgvo_gdpr/lang_de.inc.php
serendipity_event_dsgvo_gdpr/lang_en.inc.php

The cookie consent banner is a notice to inform users about our usage of cookies - it's not a way to get consent, because cookies are used whether you click "accepted" or not. The click will just dismiss the banner.
As we do not really ask for consent - if we did, we had to refrain from setting cookies unless and until the users has accepted -, we shouldn't make it sound like we do. Anything else would IMO violate the GDPR requirement of "information [...] in a concise, transparent, intelligible and easily accessible form, using clear and plain language" (Art. 12).
So, "I understand" (or "dismiss") instead of "I accept".
Incidentally, I do not think that we need explicit consent for the usage of cookies to the extent that we do so. However, if we should need consent for legal reasons, …

Cookie Consent: "understood", not "accepted".

---

serendipity_event_multilingual/ChangeLog
serendipity_event_multilingual/serendipity_event_multilingual.php

empty search was no covered and showed the blog title and description in the {{  }} format unprocessed

assign lang stripped blogTitle in genpage hook

---

serendipity_event_dsgvo_gdpr/ChangeLog
serendipity_event_dsgvo_gdpr/serendipity_event_dsgvo_gdpr.php

Currently, legal information for plugins is only shown when it had not been cached. As most plugin info will be cached, nothing's shown.
We have to bypass the cache and query all installed plugins directly to make that work.
Fixes s9y/Serendipity#572.

[event_dsgvo_gdpr] Display plugin legal info.

---

serendipity_event_markdown/ChangeLog
serendipity_event_markdown/serendipity_event_markdown.php

Undo replacing of ">" (by "&gt;"), done by serendipity_event_unstrip_tags, at the beginning of the line in comments to make blockquotes possible.

[markdown] Make blockquotes in comments usable.

---

serendipity_event_google_sitemap/serendipity_event_google_sitemap.php

Change the URLs that are HTTPS now to use that directly and avoid redirects.
Also remove the deprecated ask.com submission URL.

Change URLs to HTTPS and remove old ask.com URL

---

serendipity_event_google_sitemap/serendipity_event_google_sitemap.php

This should fix the errors I reported here:
https://board.s9y.org/viewtopic.php?f=3&t=24196
The problem in the code is this: The sitemap xmlns was included conditionally if $gnewsmode is set. However that is only the case for the separate gnews sitemap.
In the case of gnews_single - where the news items are included in the main sitemap - it's not. But it is still required.
There's a check for that and it sets $this->gnewsmode, but after that block, so I had to switch those code blocks around and change the if($gnewsmode) to if($this->gnewsmode).
Please merge.

set xmlns for sitemap-news also with gnews_single mode

---

serendipity_event_social/ChangeLog
serendipity_event_social/serendipity_event_social.php

Google+ has been shutdown 2019-04-02.

Remove Google+ from Shariff.

---

serendipity_event_staticpage/serendipity_event_staticpage.php

I found several warnings like this in my logs:
```
PHP Warning:  Use of undefined constant INCLUDE_ANY - assumed 'INCLUDE_ANY' (this will throw an Error in a future version of PHP) in [path]/plugins/serendipity_event_staticpage/serendipity_event_staticpage.php on line 2560
```
For all I can tell INCLUDE_ANY is actually meant to be an array index and not a constant. (However I'm not sure what it does, maybe this is just obsolete, there were other such code pieces in the past, but this is the only one left, and a comment in template_api.inc.php indicates $security_settings is unused.)

INCLUDE_ANY should be an array index, not a constant

---

serendipity_event_customarchive/serendipity_event_customarchive.php

In the customarchive plugin, i choosed the option "display as article". But despite that option, the title had no margin on the left side. I looked at the formatting and it was quite different than an article with the 2k11 theme. So, i changed the formatting, choosing the same html tags and classes than said theme. I also linked the title to itself because that is according to the normal articles.

customarchive: changed the formatting of the output

---

serendipity_event_entrylastmodified/serendipity_event_entrylastmodified.php

My database has some last_modified entries just containing the year (2004, as it is) or "0", leading to wrong "last modified" dates in January, 1970 (2004) or displaying the current date and time for "last modified". A simple check can catch those wrong entries, as there can't be any valid modification dates before 1990 (not even after an import from some older blog software).
I *could* fix my database instead, but I'm not sure of the reason for those entries; they may be artifacts of my initial import into s9y or from older plugin or s9y versions. This sanity check doesn't hurt, I think.

Catch wrong last_modified dates.

---

serendipity_event_metadesc/ChangeLog
serendipity_event_metadesc/serendipity_event_metadesc.php

Properties where deleted from the database when the property was present in the database and it wasn't changed. That seems wrong.
A property should only be deleted if it is set in the database, but not set in the POST request.

metadesc: Fix logic for INSERT/UPDATE/DELETE.

---

emerge_spartacus.php

netmirror.org is no longer used in spartacus.
FTP connects fail anyway.

emerge_spartacus: remove netmirror upload.

---

serendipity_event_metadesc/ChangeLog
serendipity_event_metadesc/serendipity_event_metadesc.php

8155626bd66604dc9097b83b98a44ff772acbec6 will lead to empty db queries if all properties are unchanged.
Fix that.

metadesc: Rellay fix INSERT/UPDATE/DELETE logic.

---

serendipity_event_autoupdate/ChangeLog
serendipity_event_autoupdate/UTF-8/lang_de.inc.php
serendipity_event_autoupdate/UTF-8/lang_en.inc.php
serendipity_event_autoupdate/lang_de.inc.php
serendipity_event_autoupdate/lang_en.inc.php
serendipity_event_autoupdate/serendipity_event_autoupdate.php

Add an option to the plugin settings that allows to disable the file integrity checks _for one run_ of the auto updater. The option is reset immediately to ensure the file integrity checks are performed the next time the auto updater is run.
So if anyone experiences the issue linked below, we can point them to this option.
Addresses [this issue](https://board.s9y.org/viewtopic.php?f=1&t=24492&sid=797753f16261c7ed4fe71f252c0de1ce).

[event_autoupdate] Add option to disable file integrity checks

---

serendipity_event_geotag/ChangeLog
serendipity_event_geotag/plugin_version.inc.php
serendipity_event_geotag/serendipity_event_geotag.php

Adds onpaste events to handle copied geodata.
Example 1 - Pasting `51.48165, 7.2164"` into lat:
Example 2 - Pasting `12.37129 / 51.33962` into long:

[event_geotag] onpaste event applies "lat,long" values

---

homepage/index.php

* RSS feed links to netmirror are long dead; use Github instead.
* The linked privacy policy is gone, too. Use the same page as everywhere else.
* We are not hosted by SourceForge any longer.
* Keep currently selected page when changing language, but change language for that page on the fly.

Fix some long dead links, enhance language chooser.

---

homepage/index.php

Due to the long list of themes, language selector and feed list are way, way down and can easily be overlooked. Move at least the language selector up to the top. (We could also cut the complete list of themes in the sidebar.)

Move language selector to top of sidebar.

---

serendipity_event_social/ChangeLog
serendipity_event_social/UTF-8/lang_de.inc.php
serendipity_event_social/UTF-8/lang_en.inc.php
serendipity_event_social/lang_de.inc.php
serendipity_event_social/lang_en.inc.php
serendipity_event_social/serendipity_event_social.php

_event_social_ will use the first image from the entry for the OpenGrahp "og:image" meta property used by Facebook and Twitter; if there is none, it will fall back to the default image from the plugin configuration. The timeline and photo themes support setting a featured image that is used instead.
Add the possibility to set a social media image for each entry, regardless of theme. If there is none set, fall back to timeline or photo featured images, or the first image in the entry body, or the default image from the plugin configuration (in that order).

[event_social] Set social media image for entry.

---

serendipity_event_podcast/ChangeLog
serendipity_event_podcast/player/getid3/getid3.lib.php
serendipity_event_podcast/serendipity_event_podcast.php

PHP 7 doesn't accept `break` statements outside of loop or switch structures and
returns an error. See https://www.php.net/manual/en/control-structures.break.php
I substituted the `break` by a `return false` which as far as I assume does the same.

substitute break outside of a loop by `return false`

---

serendipity_event_staticpage/ChangeLog
serendipity_event_staticpage/serendipity_event_staticpage.php

Fixes PHP 8 compatibility through the main path of the plugin: Install, backend menu, site generation, site display.
Also tries to fix the feature introduced in the last version of ignoring GET params for staticpage detection.
Needs additional testing.

staticpage 4.15.6: PHP 8 compatibility & page params fix

---

serendipity_event_freetag/serendipity_event_freetag.php

I got a warning about an undefined variable $cond in serendipity_event_freetag.php.
This looks like it's just a typo. Through a loop various things are appended via "$cond .= ..." and at the beginning $ccond is set to an empty string. $ccond isn't used anywhere else. It was probably intended here to set $cond to an empty string instead of $ccond.

freetag: Fix typo, cond instead of ccond, avoids undefined var error

---

serendipity_event_markdown/ChangeLog
serendipity_event_markdown/lib/License.md
serendipity_event_markdown/lib/Michelf/Markdown.php
serendipity_event_markdown/lib/Michelf/MarkdownExtra.php
serendipity_event_markdown/lib/Michelf/MarkdownInterface.php
serendipity_event_markdown/lib/Readme.md
serendipity_event_markdown/lib/Readme.php
serendipity_event_markdown/lib/composer.json
serendipity_event_markdown/serendipity_event_markdown.php

Upgrade bundled markdown lib `michelf/php-markdown` to version 1.9.1 that enables PHP 8 compatibility. Also dump support for EOL PHP versions in serendipity_event_markdown, because the new version of the bundled markdown lib raises the required PHP version to PHP >=7.4.

markdown: upgrade php-markdown for PHP 8.0/8.1 compatibility

---

serendipity_plugin_imagesidebar/ChangeLog
serendipity_plugin_imagesidebar/media_sidebar.php
serendipity_plugin_imagesidebar/serendipity_plugin_imagesidebar.php

Fixes the plugin for s9y 2.4 (and it still works in 2.3.5)

imagesidebar 0.100.3: Fix permanent display of unknown mime icon

---

serendipity_event_freetag/serendipity_event_freetag.php

By sending a tag variable that is an array one can trigger an uncaught exception. I saw these in my logs, likely due to some internet scans.
This can be reproduced like this:
```
curl 'https://[host]/rss.php?serendipity\[tag\]\[\]=1'
```
Fixing this by checking that the var is actually a string, and ignore it otherwise.

Check that the tag GET variable is a string

---

serendipity_plugin_topexits/ChangeLog
serendipity_plugin_topexits/UTF-8/lang_en.inc.php
serendipity_plugin_topexits/serendipity_plugin_topexits.php

Add missing TOP_EXITS and SHOWS_TOP_EXIT string definitions that
lead to a blank serendipity_admin.php page under PHP 8.
See https://board.s9y.org/viewtopic.php?t=25730
Also add the IN_serendipity check, and ChangeLog.

Fix blank admin page with PHP8

---

serendipity_event_statistics/ChangeLog
serendipity_event_statistics/lang_en.inc.php
serendipity_event_statistics/serendipity_event_statistics.php

Undefined language constants TOP_REFERRER and TOP_EXITS lead to
uncaught error, apparently assumed to be available via
serendipity_plugin_entrylinks.
Create and use proper PLUGIN_EVENT_STATISTICS_TOP_REFERRER and
PLUGIN_EVENT_STATISTICS_TOP_EXITS constants.

Fix broken admin page with PHP8

---

serendipity_event_linktrimmer/ChangeLog
serendipity_event_linktrimmer/serendipity_event_linktrimmer.php

is_countable() would demand PHP >= 7.3.0 as of which it is available.
See https://www.php.net/manual/en/function.is-countable.php
Use a polyfill for PHP < 7.3.0
Loading serendipity_admin.php with $serendipity['production'] = false
yielded a red alert box:
The Serendipity JavaScript-library could not be loaded. This can happen
due to PHP or Plugin errors, or even a malformed browser cache. To check
the exact error please open
https://.../index.php?/plugin/admin/serendipity_editor.js manually in
your browser and check for error messages.
Where at the end of that file could be found:
== ERROR-REPORT (BETA/ALPHA-BUILDS) ==
<p><b>Warning:</b> count(): Parameter must be an array or an object that
implements Countable in
plugins/serendipity_event_linktrimmer/serendipity_event_linktrimmer.php
on …

Check is_countable() before count()

---

serendipity_event_geshi/ChangeLog
serendipity_event_geshi/serendipity_event_geshi.php

* Serendipity 2.4.0
* serendipity_event_geshi 1.1.1
Some of my blog entries don't seem to have any _properties_ and produced warnings in the HTTP server log like these:
```
[Wed Jul 12 22:33:30.225879 2023] [php:warn] [pid 517606] [client […]] PHP Warning:  Trying to access array offset on value of type null in […]/plugins/serendipity_event_geshi/serendipity_event_geshi.php on line 153, referer: […]
[Wed Jul 12 22:33:31.617569 2023] [php:warn] [pid 517606] [client […]] PHP Warning:  Undefined array key "propertie..s" in […]/plugins/serendipity_event_geshi/serendipity_event_geshi.php on line 153, referer: […]
```
Adding `isset()` to the referenced line of code fixes the warnings for me.
My Geshi code blocks still render as before.

serendipity_event_geshi: fix warning when $eventData contains no properties

---

serendipity_event_spamblock_bayes/serendipity_event_spamblock_bayes.php

Alter the token column in the b8_wordlist to a case-sensitive collation to prevent duplicate key errors when the same token is encountered in different cases (e.g. 'the', 'THE' and 'ThE').
The PHP code compares tokens case-sensitive when deciding whether to do an INSERT or UPDATE, so the database also needs to be case-sensitive.
After finding out that the collation update fixes my primary key constraint violations, I've done these test steps to ensure the code change does indeed apply the collation update as desired:
1. I renamed my `b8_wordlist` table to `b8_wordlist_SAVE` (because I have no separate blog for testing, I had to use my live blog)
2. Calling the comments page in the administration ran the `setupDB()` function
3. The missing `b8_wordlist` table was recreated.
4. `SHOW FULL …

spambayes: make tokens case-sensitive on MySQL

---

serendipity_event_commentedit/ChangeLog
serendipity_event_commentedit/serendipity_event_commentedit.js
serendipity_event_commentedit/serendipity_event_commentedit.php

Intended to finally make jQuery upgrade possible, see https://github.com/s9y/Serendipity/pull/687#issuecomment-798926814
@garvinhicking Could you have a look at the plugin in the new state? I remembered this plugin as a hack that probably wasn't secure. Seeing the code now, I actually could not identify a security issue - it seems to properly rely on the session having the commentid, which is supplied by the backend code and not the user.
The fixes here should make the plugin work again, and avoid issues with newer jQuery options. But a valid alternative is to just remove the plugin, especially if you see issues  that can't be fixed.

commentedit: Improve compatibility with browsers

---

serendipity_event_flickr/ChangeLog
serendipity_event_flickr/phpFlickr/phpFlickr.php
serendipity_event_flickr/serendipity_event_flickr.php

serendipity_event_flickr was completely broken since it relied on HTTP_Request, which we had removed. It's the one remainder listed in https://github.com/s9y/Serendipity/issues/550, as the fix was not all that easy. 
This PR updates the bundled phpFlickr library to the latest version from https://github.com/dan-coulter/phpflickr. It applies additional patches to make the library actually work again (with PHP 8 and in general), and fixes the plugin code to work with those changes. Also contains a few fixes for warnings under PHP 8.
phpFlickr had previously been patched manually to use our HTTP_Request. The new version instead tries to use curl or sockets directly. I think that's okay, and we can simply not patch in HTTP_Request2 or serendipity_request_url, the current state should work …

flickr 1.0: Restore functionality and make compatible with PHP 8

---

serendipity_event_lazyoutube/ChangeLog
serendipity_event_lazyoutube/README.md
serendipity_event_lazyoutube/UTF-8/lang_de.inc.php
serendipity_event_lazyoutube/UTF-8/lang_en.inc.php
serendipity_event_lazyoutube/lang_de.inc.php
serendipity_event_lazyoutube/lang_en.inc.php
serendipity_event_lazyoutube/serendipity_event_lazyoutube.php

This plugin seems to have been in use on my blog for 4 years oO I absolutely did not realize it was so old already.
It replaces the regular youtube embeds with a new custom embed that does not load the video player directly, but only on click. This provides a huge performance boost when a blog has multiple youtube embeds, and it limits how much access Youtube gets to visitors that do not interact with the videos ([see my article](https://www.onli-blogging.de/2040/YouTube-Videos-einbinden,-ohne-dass-die-Seite-lahm-wird-+Serendipity-Plugin.html)).
I recently extended the plugin to also proxy that thumbnail image, so that the visitor's IP really only reaches Youtube iff the user clicks on the video. That code could use a review, if possible. 
It might be a good idea to extend that thumbnail …

lazyoutube: Init plugin on spartacus

---

serendipity_event_staticpage/ChangeLog
serendipity_event_staticpage/backend_templates/default_staticpage_backend.tpl
serendipity_event_staticpage/serendipity_event_staticpage.php

The staticpage plugin was always throwing an error on installation. The error did not block the plugin from working, on a reload the database was fully created, but the logic of how upgrades and fresh installs works was broken. This fixes the error by only creating a minimal table and upgrading it with the same alter statements that an old plugin installation would go through.
Also fixes the upgrade process when using sqlite. Sqlite can add columns since 2005, but it was blocked here from doing so without providing an alternative. I removed the checks for the db type.
Plus some fixes for PHP 8 warnings and the smarty escape error reported in https://github.com/s9y/Serendipity/issues/863.

staticpage 4.15.10: Reworked table creation/upgrade, smarty escape fix, PHP 8 fixes

---

serendipity_event_guestbook/ChangeLog
serendipity_event_guestbook/serendipity_event_guestbook.php
serendipity_event_guestbook/serendipity_plugin_guestbook.php

Fixes multiple warnings that the plugin produces under PHP 8, including the one reported in https://github.com/s9y/Serendipity/issues/718.
Also replaces the custom email check with `filter_var` and makes use of the cores `serendipity_specialchar` instead of using a copy inside the plugin code.

guestbook 3.61.3: Fixes for PHP 8 warnings

---

serendipity_event_google_sitemap/ChangeLog
serendipity_event_google_sitemap/serendipity_event_google_sitemap.php

Using proper intval() when estimating most recent timestamp. This won't crash on NULL values.
This is a cleaned up PR copy of https://github.com/s9y/additional_plugins/pull/168.

sitemap 0.61.4: Fix error with null timespams on PHP 8

---

serendipity_event_google_sitemap/ChangeLog
serendipity_event_google_sitemap/serendipity_event_google_sitemap.php

Fixes the issues reported in https://github.com/s9y/Serendipity/issues/862. To avoid gmstrftime this PR proposes using `date` instead. This does change the format of the resulting formatted timestamp, from 2025-06-24T20:10:03Z to 2025-06-24T22:11:48+02:00. But this should be fine, https://www.sitemaps.org/protocol.html#lastmoddef specifies https://www.w3.org/TR/NOTE-datetime as the wanted format, and the changed timezone indicator is in spec:
> TZD  = time zone designator (Z or +hh:mm or -hh:mm)
To make the code easier to maintain this also removes the various backwards compatibility shims that should not be needed anymore. Serendipity 2.0 is thus set as the new required version.

sitemap 1.0: Solve deprecation warnings

---

serendipity_event_adminnotes/ChangeLog
serendipity_event_adminnotes/serendipity_event_adminnotes.php

As reported in https://board.s9y.org/viewtopic.php?p=10459357&sid=fe8e1111a01569edef956807cf045376#p10459357, the adminnotes plugin had an incompatibility with PHP 8.x, calling `count(null)`. This PR fixes that error, some additional warnings, and removes the checks for s9y 1.x to simplify future maintenance a bit.

adminnotes 0.16.2: PHP 8 compatibility fixes and bc layer removal

---

serendipity_plugin_timezones/ChangeLog
serendipity_plugin_timezones/UTF-8/lang_bg.inc.php
serendipity_plugin_timezones/UTF-8/lang_cs.inc.php
serendipity_plugin_timezones/UTF-8/lang_cz.inc.php
serendipity_plugin_timezones/UTF-8/lang_de.inc.php
serendipity_plugin_timezones/lang_bg.inc.php
serendipity_plugin_timezones/lang_cs.inc.php
serendipity_plugin_timezones/lang_cz.inc.php
serendipity_plugin_timezones/lang_de.inc.php
serendipity_plugin_timezones/lang_en.inc.php
serendipity_plugin_timezones/serendipity_plugin_timezones.php

https://board.s9y.org/viewtopic.php?p=10459385#p10459385 reported that the timezones plugin broke under PHP 8.4. The plugin used two different approach for its work, either https://pear.php.net/package/Date, but without actually including the needed Date.php file, or a `time()` with offset approach. This PR instead uses `DateTimeImmutable` with timezone names (these: https://www.php.net/manual/de/timezones.php) and drops the manual offset.

timezones 1.0: Avoid PHP error, use DateTime instead of Date.php
